name: lost_and_found
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

analyzer:
  enable-experiment:
    - non-nullable

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.10.0 
  firebase_auth: ^3.2.0 
  google_sign_in: ^5.2.1  
  cupertino_icons: ^1.0.4
  mongo_dart: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
    - assets/track_it_logo.jpg

  fonts:
    - family: Trueno
      fonts:
        - asset: fonts/TruenoExBd.otf
